complete -c odx -f

complete -c odx -n "__fish_use_subcommand" -a help -d "Ayuda"
complete -c odx -n "__fish_use_subcommand" -a up -d "Levantar contenedores"
complete -c odx -n "__fish_use_subcommand" -a down -d "Bajar contenedores"
complete -c odx -n "__fish_use_subcommand" -a deps -d "Instalar dependencias"
complete -c odx -n "__fish_use_subcommand" -a addons -d "Sincronizar addons"
complete -c odx -n "__fish_use_subcommand" -a run -d "Ejecutar odoo-bin --dev=all"
complete -c odx -n "__fish_use_subcommand" -a update -d "Actualizar módulos"
complete -c odx -n "__fish_use_subcommand" -a restore -d "Restaurar ZIP Odoo con filestore"
complete -c odx -n "__fish_use_subcommand" -a db -d "Gestionar bases de datos"
complete -c odx -n "__fish_seen_subcommand_from db; and not __fish_seen_subcommand_from list restore drop" -a list -d "Listar bases de datos"
complete -c odx -n "__fish_seen_subcommand_from db; and not __fish_seen_subcommand_from list restore drop" -a restore -d "Restaurar ZIP Odoo con filestore"
complete -c odx -n "__fish_seen_subcommand_from db; and not __fish_seen_subcommand_from list restore drop" -a drop -d "Eliminar bases y filestores"
complete -c odx -n "__fish_seen_subcommand_from db; and __fish_seen_subcommand_from list drop" -l pattern -r -f -d "Patrón glob (por ejemplo test_*)"
complete -c odx -n "__fish_seen_subcommand_from db; and __fish_seen_subcommand_from list drop" -l exclude -r -f -d "Nombre exacto a excluir; repetible"
complete -c odx -n "__fish_seen_subcommand_from db; and __fish_seen_subcommand_from drop" -s d -l db -r -f -d "Base de datos a eliminar"
complete -c odx -n "__fish_seen_subcommand_from db; and __fish_seen_subcommand_from drop" -l all -d "Todas las bases elegibles"
complete -c odx -n "__fish_seen_subcommand_from db; and __fish_seen_subcommand_from drop" -l dry-run -d "Previsualizar sin eliminar"
complete -c odx -n "__fish_seen_subcommand_from db; and __fish_seen_subcommand_from drop" -s y -l yes -d "Omitir confirmación"
complete -c odx -n "__fish_seen_subcommand_from db; and not __fish_seen_subcommand_from restore" -s h -l help -d "Ayuda de gestión de bases"
complete -c odx -n "__fish_seen_subcommand_from restore" -F
complete -c odx -n "__fish_seen_subcommand_from restore" -s d -l db -r -f -d "Base de datos destino"
complete -c odx -n "__fish_seen_subcommand_from restore" -s p -l password -r -f -d "Password del admin restaurado (por defecto: admin)"
complete -c odx -n "__fish_seen_subcommand_from restore" -l force -d "Eliminar DB y filestore existentes"
complete -c odx -n "__fish_seen_subcommand_from restore" -l no-neutralize -d "No neutralizar la copia"
complete -c odx -n "__fish_seen_subcommand_from restore" -s h -l help -d "Ayuda de restore"
complete -c odx -n "__fish_use_subcommand" -a passwd -d "Resetear contraseña"
complete -c odx -n "__fish_use_subcommand" -a reset-password -d "Alias de passwd"
complete -c odx -n "__fish_use_subcommand" -a sh -d "Entrar al contenedor odoo"
complete -c odx -n "__fish_use_subcommand" -a logs -d "Ver logs"
complete -c odx -n "__fish_use_subcommand" -a doctor -d "Ver diagnóstico"
complete -c odx -n "__fish_use_subcommand" -a root -d "Mostrar raíz detectada"

complete -c odx -n "__fish_seen_subcommand_from update" -s d -l db -r -d "Nombre de base de datos"
complete -c odx -n "__fish_seen_subcommand_from update" -s u -l modules -r -d "Módulos a actualizar"
complete -c odx -n "__fish_seen_subcommand_from update" -s h -l help -d "Ayuda de update"

complete -c odx -n "__fish_seen_subcommand_from passwd reset-password" -s d -l db -r -d "Nombre de base de datos"
complete -c odx -n "__fish_seen_subcommand_from passwd reset-password" -s u -l user -r -d "Login del usuario"
complete -c odx -n "__fish_seen_subcommand_from passwd reset-password" -s p -l password -r -d "Nueva contraseña"
complete -c odx -n "__fish_seen_subcommand_from passwd reset-password" -s h -l help -d "Ayuda de passwd"
